'use strict';
const config={
    detail:{
        desc:"配置详细信息",
        publicVersion:{
            desc:"版本发布管理"
        },
        version:{
            desc:"显示版本信息"
        },
        help:{
            desc:"显示使用方法"
        },
        template:{
            desc:"模板管理"
        },
        excelToJson:{
            desc:"excel,json互转"
        },
        dataDeal:{
            desc:'数据处理'
        },
        cordova:{
            desc:"cordova 移动app处理方法"
        },
        xml:{
            desc:"xml类文件解析，编辑，修改，生成等操作"
        },
        file:{
            desc:"常用文件处理操作"
        }
    },
    sum:["version","help","template","publicVersion","excelToJson","dataDeal","cordova","xml","file"],
    simpled:{
        desc:"命令简写",
        H:"help",
        PV:"publicVersion",
        V:"version",
        temp:"template"
    }
};
module.exports={
    config
}